---
- hosts: dbnodes

  vars:
    http_port: 80
    max_clients: 200

  remote_user: root

  tasks:
  - name: mariadb install
    yum: name=mariadb-server state=latest
    notify: mariadb start
  - name: redis install
    yum: name=redis state=latest
    template: src=redis.j2 dest=/etc/redis.conf owner=redis mode=640
    notify: redis start

  handlers:
  - name: mariadb start
    service: name=mariadb state=started enabled=true
  - name: redis start
    service: name=redis state=started enabled=true
